server:
  port: 8761

spring:
  application:
    name: "eurekaserver"
  cloud:
    config:
      enabled: false

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true