services:
  eurekaserver:
    image: "eurekaserver"
    container_name: "eurekaserver-ms"
    ports:
      - "8761:8761"
    healthcheck:
      test: "curl --fail --silent http://eurekaserver-ms:8761/actuator/health/readiness || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eroom
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  gateway_server:
    image: "gateway"
    container_name: "gateway-ms"
    ports:
      - "9104:9104"
    healthcheck:
      test: "curl --fail --silent http://gateway-ms:9104/actuator/health/readiness || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    depends_on:
      eurekaserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eroom
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver-ms:8761/eureka/
  #      - SPRING_PROFILES_ACTIVE=docker

  mdm_service:
    image: "mdm-service"
    container_name: "mdm-service-ms"
    ports:
      - "9101:9101"
    depends_on:
      eurekaserver:
        condition: service_healthy
      gateway_server:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eroom
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver-ms:8761/eureka/
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.29.113:5432/eroom
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root

  user_auth:
    image: "user-auth"
    container_name: "user-auth-ms"
    ports:
      - "9102:9102"
    depends_on:
      eurekaserver:
        condition: service_healthy
      gateway_server:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eroom
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver-ms:8761/eureka/
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.29.113:5432/eroom
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root

networks:
  eroom:
    driver: "bridge"
