spring:
  datasource:
    url: jdbc:postgresql://172.20.9.5:5432/eroom_uat
    username: eroom
    password: Eroom@xyz
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Kolkata

# JWT Details
jwtSecret: bpat528@1342#eroom@Bpaas@2024&@025
accessTokenExpiryTime: 14400000

# Backend server details
backendServerDetail: http://172.20.5.85:9100


# Log path
logging:
  file:
    path: /DMS/eroom/logs