spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/eroom
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Kolkata

# JWT Details
jwtSecret: bpat528@1342#eroom@Bpaas@2024&@025
accessTokenExpiryTime: 14400000


